config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:new, :create, :index]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, :address,:category,  presence: true
  validates :category, inclusion: { in: %w(chinese italian japanese french belgian)}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    redirect_to task_path(@task)
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant

  def index
    @reviews = Review.all
  end



  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    @review.save
    redirect_to restaurant_path(@restaurant)

  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Welcome to Restaurants</h1>
<% @restaurants.each do |restaurant| %>
<li><%= restaurant.name %> <%= restaurant.address %></li>
<p><%= link_to "Show this restaurant", restaurant,class: "btn btn-primary" %></p>
<% end %>

app/views/restaurants/show.html.erb
<div class=container>
<h1><%= @restaurant.name  %></h1>
<h2><%= @restaurant.address %></h2>
<h2><%= @restaurant.category %></h2>

<p><%= link_to "back to restaurants", restaurants_path,class: "btn btn-primary" %></p>
<p><%= link_to "new review", new_restaurant_review_path(@restaurant),class: "btn btn-primary" %></p>
<p><%= link_to "see reviews", restaurant_reviews_path(@restaurant),class: "btn btn-primary" %></p>
</div>

app/views/reviews/index.html.erb
<div class="container">
<h1><%= @restaurant.name %></h1>
  <ul class="list-group">
    <% @restaurant.reviews.each do |review| %>
      <li class="list-group-item">Descripcion: <%= review.content %> Rating:<%= review.rating %></li>
    <% end %>
  </ul>
    <p><%= link_to "back to restaurant", restaurant_path(@restaurant),class: "btn btn-primary" %></p>
  <br>

</div>

app/views/reviews/new.html.erb
<h1>New review</h1>
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, as: :integer %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>